// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Copyright Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright_text: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Navigation Links*
 */
export interface HeaderDocumentDataNavigationLinksItem {
  /**
   * Caption field in *Header → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_links[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;

  /**
   * Link field in *Header → Navigation Links*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.ContentRelationshipField;

  /**
   * Anchor DIV field in *Header → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_links[].anchor_div
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor_div: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Navigation Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation_links: prismic.GroupField<
    Simplify<HeaderDocumentDataNavigationLinksItem>
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type IndexDocumentDataSlicesSlice =
  | LogosSlice
  | CallToActionSlice
  | ExperienceBlockSlice
  | ContactFormSlice
  | AlignedTextBlockSlice
  | ProsIconsBlockSlice
  | PricingSlice
  | HowItWorksSlice
  | ProsListBlockSlice
  | TextBlockSlice
  | HeroBannerSlice;

/**
 * Content for Index documents
 */
interface IndexDocumentData {
  /**
   * Slice Zone field in *Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

/**
 * Item in *Partials → Socials*
 */
export interface PartialsDocumentDataSocialsItem {
  /**
   * Icon field in *Partials → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.socials[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Partials → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.socials[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Caption field in *Partials → Socials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.socials[].caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Content for Partials documents
 */
interface PartialsDocumentData {
  /**
   * Socials field in *Partials*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<PartialsDocumentDataSocialsItem>>;

  /**
   * Logo field in *Partials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Checked Icon field in *Partials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.checked_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  checked_icon: prismic.ImageField<never>;

  /**
   * Unchecked Icon field in *Partials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partials.unchecked_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  unchecked_icon: prismic.ImageField<never>;
}

/**
 * Partials document from Prismic
 *
 * - **API ID**: `partials`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartialsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PartialsDocumentData>,
    "partials",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | IndexDocument
  | PartialsDocument;

/**
 * Primary content in *AlignedTextBlock → Primary*
 */
export interface AlignedTextBlockSliceDefaultPrimary {
  /**
   * Title field in *AlignedTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aligned_text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraphs field in *AlignedTextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: aligned_text_block.primary.paragraphs
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphs: prismic.RichTextField;

  /**
   * Image field in *AlignedTextBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: aligned_text_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for AlignedTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlignedTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlignedTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AlignedTextBlock*
 */
type AlignedTextBlockSliceVariation = AlignedTextBlockSliceDefault;

/**
 * AlignedTextBlock Shared Slice
 *
 * - **API ID**: `aligned_text_block`
 * - **Description**: AlignedTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlignedTextBlockSlice = prismic.SharedSlice<
  "aligned_text_block",
  AlignedTextBlockSliceVariation
>;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraphs field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.paragraphs
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphs: prismic.RichTextField;

  /**
   * Button Caption field in *CallToAction → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;

  /**
   * Image field in *CallToAction → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *ContactForm → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Image field in *ContactForm → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ContactForm → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ContactForm → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Name Helper Text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.name_helper_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name_helper_text: prismic.KeyTextField;

  /**
   * Email Helper Text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.email_helper_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_helper_text: prismic.KeyTextField;

  /**
   * Phone Helper Text field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.phone_helper_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_helper_text: prismic.KeyTextField;

  /**
   * Button Caption field in *ContactForm → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.primary.button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *ExperienceBlock → Primary*
 */
export interface ExperienceBlockSliceDefaultPrimary {
  /**
   * Title field in *ExperienceBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *ExperienceBlock → Items*
 */
export interface ExperienceBlockSliceDefaultItem {
  /**
   * Image field in *ExperienceBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ExperienceBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ExperienceBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Caption field in *ExperienceBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.items[].button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;

  /**
   * Button Link field in *ExperienceBlock → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_block.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.ContentRelationshipField;
}

/**
 * Default variation for ExperienceBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienceBlockSliceDefaultPrimary>,
  Simplify<ExperienceBlockSliceDefaultItem>
>;

/**
 * Slice variation for *ExperienceBlock*
 */
type ExperienceBlockSliceVariation = ExperienceBlockSliceDefault;

/**
 * ExperienceBlock Shared Slice
 *
 * - **API ID**: `experience_block`
 * - **Description**: ExperienceBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienceBlockSlice = prismic.SharedSlice<
  "experience_block",
  ExperienceBlockSliceVariation
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Title field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraphs field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.paragraphs
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphs: prismic.RichTextField;

  /**
   * Button Caption field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;

  /**
   * Button Link field in *HeroBanner → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.ContentRelationshipField;

  /**
   * Image field in *HeroBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *HowItWorks → Primary*
 */
export interface HowItWorksSliceDefaultPrimary {
  /**
   * Title field in *HowItWorks → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *HowItWorks → Items*
 */
export interface HowItWorksSliceDefaultItem {
  /**
   * Point field in *HowItWorks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.items[].point
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  point: prismic.RichTextField;

  /**
   * Description field in *HowItWorks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *HowItWorks → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_it_works.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HowItWorks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HowItWorksSliceDefaultPrimary>,
  Simplify<HowItWorksSliceDefaultItem>
>;

/**
 * Slice variation for *HowItWorks*
 */
type HowItWorksSliceVariation = HowItWorksSliceDefault;

/**
 * HowItWorks Shared Slice
 *
 * - **API ID**: `how_it_works`
 * - **Description**: HowItWorks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HowItWorksSlice = prismic.SharedSlice<
  "how_it_works",
  HowItWorksSliceVariation
>;

/**
 * Primary content in *Logos → Primary*
 */
export interface LogosSliceDefaultPrimary {
  /**
   * Title field in *Logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Logos → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Logos → Items*
 */
export interface LogosSliceDefaultItem {
  /**
   * Logo field in *Logos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Company Name field in *Logos → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Link field in *Logos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogosSliceDefaultPrimary>,
  Simplify<LogosSliceDefaultItem>
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<"logos", LogosSliceVariation>;

/**
 * Default variation for Package Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PackageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Package*
 */
type PackageSliceVariation = PackageSliceDefault;

/**
 * Package Shared Slice
 *
 * - **API ID**: `package`
 * - **Description**: Package
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PackageSlice = prismic.SharedSlice<
  "package",
  PackageSliceVariation
>;

/**
 * Primary content in *Pricing → Primary*
 */
export interface PricingSliceDefaultPrimary {
  /**
   * Title field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Services Included field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.services_included
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  services_included: prismic.KeyTextField;

  /**
   * Start Package Name field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.start_package_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  start_package_name: prismic.KeyTextField;

  /**
   * Full Package Name field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.full_package_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_package_name: prismic.KeyTextField;

  /**
   * Start Package Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.start_package_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_package_description: prismic.RichTextField;

  /**
   * Full Package Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.full_package_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  full_package_description: prismic.RichTextField;

  /**
   * Start Package Price field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.start_package_price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_package_price: prismic.RichTextField;

  /**
   * Full Package Price field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.full_package_price
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  full_package_price: prismic.RichTextField;

  /**
   * Button Caption field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;

  /**
   * Button Link field in *Pricing → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.ContentRelationshipField;
}

/**
 * Primary content in *Pricing → Items*
 */
export interface PricingSliceDefaultItem {
  /**
   * Service field in *Pricing → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].service
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service: prismic.RichTextField;

  /**
   * Start Package Included field in *Pricing → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.items[].start_package_included
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  start_package_included: prismic.BooleanField;

  /**
   * Full Package Included field in *Pricing → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.items[].full_package_included
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  full_package_included: prismic.BooleanField;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingSliceDefaultPrimary>,
  Simplify<PricingSliceDefaultItem>
>;

/**
 * Primary content in *Pricing → Primary*
 */
export interface PricingSliceVariation2Primary {
  /**
   * Title field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Start Package Name field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.start_package_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  start_package_name: prismic.KeyTextField;

  /**
   * Full Package Name field in *Pricing → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.full_package_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_package_name: prismic.KeyTextField;

  /**
   * Start Package Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.start_package_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  start_package_description: prismic.RichTextField;

  /**
   * Full Package Description field in *Pricing → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.primary.full_package_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  full_package_description: prismic.RichTextField;
}

/**
 * Primary content in *Pricing → Items*
 */
export interface PricingSliceVariation2Item {
  /**
   * Service field in *Pricing → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].service
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service: prismic.RichTextField;

  /**
   * Service Icon field in *Pricing → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.items[].service_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_icon: prismic.ImageField<never>;
}

/**
 * Variation2 variation for Pricing Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<PricingSliceVariation2Primary>,
  Simplify<PricingSliceVariation2Item>
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault | PricingSliceVariation2;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<
  "pricing",
  PricingSliceVariation
>;

/**
 * Primary content in *ProsIconsBlock → Primary*
 */
export interface ProsIconsBlockSliceDefaultPrimary {
  /**
   * Title field in *ProsIconsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProsIconsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProsIconsBlock → Items*
 */
export interface ProsIconsBlockSliceDefaultItem {
  /**
   * Icon field in *ProsIconsBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *ProsIconsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProsIconsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ProsIconsBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProsIconsBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProsIconsBlockSliceDefaultPrimary>,
  Simplify<ProsIconsBlockSliceDefaultItem>
>;

/**
 * Primary content in *ProsIconsBlock → Primary*
 */
export interface ProsIconsBlockSliceVariation2Primary {
  /**
   * Title field in *ProsIconsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *ProsIconsBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ProsIconsBlock → Items*
 */
export interface ProsIconsBlockSliceVariation2Item {
  /**
   * Icon field in *ProsIconsBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *ProsIconsBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_icons_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Variation2 variation for ProsIconsBlock Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProsIconsBlockSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<ProsIconsBlockSliceVariation2Primary>,
  Simplify<ProsIconsBlockSliceVariation2Item>
>;

/**
 * Slice variation for *ProsIconsBlock*
 */
type ProsIconsBlockSliceVariation =
  | ProsIconsBlockSliceDefault
  | ProsIconsBlockSliceVariation2;

/**
 * ProsIconsBlock Shared Slice
 *
 * - **API ID**: `pros_icons_block`
 * - **Description**: ProsIconsBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProsIconsBlockSlice = prismic.SharedSlice<
  "pros_icons_block",
  ProsIconsBlockSliceVariation
>;

/**
 * Primary content in *ProsListBlock → Primary*
 */
export interface ProsListBlockSliceDefaultPrimary {
  /**
   * Title field in *ProsListBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_list_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraphs field in *ProsListBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_list_block.primary.paragraphs
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphs: prismic.RichTextField;

  /**
   * Image field in *ProsListBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_list_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *ProsListBlock → Items*
 */
export interface ProsListBlockSliceDefaultItem {
  /**
   * Point Icon field in *ProsListBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_list_block.items[].point_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  point_icon: prismic.ImageField<never>;

  /**
   * Point Text field in *ProsListBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pros_list_block.items[].point_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  point_text: prismic.RichTextField;
}

/**
 * Default variation for ProsListBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProsListBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProsListBlockSliceDefaultPrimary>,
  Simplify<ProsListBlockSliceDefaultItem>
>;

/**
 * Slice variation for *ProsListBlock*
 */
type ProsListBlockSliceVariation = ProsListBlockSliceDefault;

/**
 * ProsListBlock Shared Slice
 *
 * - **API ID**: `pros_list_block`
 * - **Description**: ProsListBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProsListBlockSlice = prismic.SharedSlice<
  "pros_list_block",
  ProsListBlockSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Title field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraphs field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.paragraphs
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphs: prismic.RichTextField;

  /**
   * Background Image field in *TextBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationLinksItem,
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      PartialsDocument,
      PartialsDocumentData,
      PartialsDocumentDataSocialsItem,
      AllDocumentTypes,
      AlignedTextBlockSlice,
      AlignedTextBlockSliceDefaultPrimary,
      AlignedTextBlockSliceVariation,
      AlignedTextBlockSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      ExperienceBlockSlice,
      ExperienceBlockSliceDefaultPrimary,
      ExperienceBlockSliceDefaultItem,
      ExperienceBlockSliceVariation,
      ExperienceBlockSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      HowItWorksSlice,
      HowItWorksSliceDefaultPrimary,
      HowItWorksSliceDefaultItem,
      HowItWorksSliceVariation,
      HowItWorksSliceDefault,
      LogosSlice,
      LogosSliceDefaultPrimary,
      LogosSliceDefaultItem,
      LogosSliceVariation,
      LogosSliceDefault,
      PackageSlice,
      PackageSliceVariation,
      PackageSliceDefault,
      PricingSlice,
      PricingSliceDefaultPrimary,
      PricingSliceDefaultItem,
      PricingSliceVariation2Primary,
      PricingSliceVariation2Item,
      PricingSliceVariation,
      PricingSliceDefault,
      PricingSliceVariation2,
      ProsIconsBlockSlice,
      ProsIconsBlockSliceDefaultPrimary,
      ProsIconsBlockSliceDefaultItem,
      ProsIconsBlockSliceVariation2Primary,
      ProsIconsBlockSliceVariation2Item,
      ProsIconsBlockSliceVariation,
      ProsIconsBlockSliceDefault,
      ProsIconsBlockSliceVariation2,
      ProsListBlockSlice,
      ProsListBlockSliceDefaultPrimary,
      ProsListBlockSliceDefaultItem,
      ProsListBlockSliceVariation,
      ProsListBlockSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
