// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aligned_text_block: dynamic(() => import("./AlignedTextBlock")),
  contact_form: dynamic(() => import("./ContactForm")),
  experience_block: dynamic(() => import("./ExperienceBlock")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  how_it_works: dynamic(() => import("./HowItWorks")),
  pricing: dynamic(() => import("./Pricing")),
  pros_icons_block: dynamic(() => import("./ProsIconsBlock")),
  pros_list_block: dynamic(() => import("./ProsListBlock")),
  text_block: dynamic(() => import("./TextBlock")),
};
